### ISSUE TITLE
[Feature] Support inputting multiple points (in a list) with PrimBox.inspect()

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#124]
Instead of only inspecting one point, it would be neat if you can pass multiple points into the [`inspect()`](https://github.com/quaquel/EMAworkbench/blob/master/ema_workbench/analysis/prim.py#L405) function of an `analysis.prim.PrimBox`. The expected behavior could be:

- [x] For `PrimBox.inspect(i=list, style="table")`, a dataframe with a row for each point will be provided.
- [ ] For `PrimBox.inspect(i=list, style="graph")`, either Figure with a subplot for each point could be provided, or a single graph with the multiple points compared to each other (each point with a different color bars).

This will allow to more quickly inspect and compare multiple points on the peeling trajectory.

Also I noted that the inspect function prints a lot of data without returning it. I think it's nicer and more expected to return the values/tables/graphs, and let the user print them. That way you can use them in further analysis if you want.

**Comment by quaquel** [comment]
Implementing this is largely straightforward. Basically move most of the current code in `inspect` into some protected function `_inspect`, and then possibly loop over this depending on whether `i` is an integer or a list.

If we want to also control for `style='graph'` whether to show each box as a separate figure or have them in a single figure, then things become messier. My hunch is that it would actually break the current visualization, because of overplotting the values of the box limits as well as having to handle multiple quasi-p values (one for each box lim). 

Not sure what you mean exactly by your last remark. Given that the printing to screen is a bit more involved than simply creating the DataFrame (see [line 455 in prim.py](https://github.com/quaquel/EMAworkbench/blob/ebdbc9f5c77693fc75911ead472b420065dfe2aa/ema_workbench/analysis/prim.py#L455) ). There is a usecase for returning a DataFrame-like representation of the box lims which you can then send this to the clipboard for use in a report or something. I would, however, be inclined to treat that as a third option for the `style` kwarg.

**Comment by EwoutH** [comment]
Let's move the `"graph"` part to 2.4.0, as part of a larger plotting overhaul.
