### ISSUE TITLE
Provide instructions how to cite the EMAworkbench

### ISSUE THREAD

**Issue by EwoutH** [quaquel/EMAworkbench#198]
Since the EMAworkbench is used in academic research, it's probably useful to provide instructions on how to cite the EMAworkbench.

The easiest form would be adding a [CITATION file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) to the repository, and mention it in the Readme. The GitHub UI will than also show instructions how to cite in APA and BibTeX formats.

**Comment by EwoutH** [comment]
@quaquel Also missed this in todays meeting, could you take a look at this?

**Comment by quaquel** [comment]
I just added a citation file in a separate branch. I have used my 2017 paper as the default thing to cite, although we might want to make it possible to also cite the library itself, including the version. This is a bit tricky because we want to avoid duplicating the version number so we might have to setup some automation that inserts the version number into the citation file.

**Comment by EwoutH** [comment]
Perfect, we can take a look at that later
