### ISSUE TITLE
Logging in v2 is slow

### ISSUE THREAD

**Issue by jpn--** [quaquel/EMAworkbench#37]
Logging in the v2 branch is very slow, as it is calling into "inspect" multiple times for every debug message, regardless if debug logging is on or not.

**Comment by quaquel** [comment]
I had not realised my changes to logging made it slow, but I am not surprised. The main thing I am changing is to move from a single logger for the entire ema_workbench package, to loggers at module level. This is considered to be python best practice, hence the change. It also makes it easier to filter logging for specific modules. So *e.g.,* you can log to debug but only show log message from the experiment_runner.py module. 

At the same time, I had these info, debug, etc. wrapper functions around the package logger. Rather than having to change calls to these functions in each module, I quickly fixed it with inspect. Clearly this was much more expensive than I had anticipated. 

Probably, the more elegant fix, and the one consistent with python best practice is to remove the info, debug, etc. functions from ema_logging.py, and fix each of the modules separately. This is probably 10 minutes of work. 

I don't mind merging your change first, after which I do the above. But I will think about it a bit more over the coming days.

**Comment by quaquel** [comment]
This is now fixes more substantive in the V2 branch. I have gotten rid of the reflection all together as well as the convenience logging functions in ema_logging.
