### ISSUE TITLE
issure: get only one  solution when running evaluator.optimize()

### ISSUE THREAD

**Issue by yjx4131** [quaquel/EMAworkbench#59]
when I run the following codes in jupyterLab I can find only one solution every time. However, if I run them in an IDE I can find multiple solutions as described in your documentation. No matter which version of EMA I use to run the code.

```
from ema_workbench import Constraint
constraints = [Constraint("max pollution", outcome_names="max_P",function=lambda x:max(0, x-1))]
from ema_workbench import MultiprocessingEvaluator
from ema_workbench import ema_logging
with MultiprocessingEvaluator(model) as evaluator:
    results = evaluator.optimize(nfe=250, searchover='levers',epsilons=[0.1,]*len(model.outcomes),constraints=constraints)
```

**Comment by quaquel** [comment]
You need to give me more information to understand what is going on. 
* Which model are you using?
* which IDE do you use?
* Are the IDE and Jupyter lab using the same python version
* have you tried explicitly setting numpy.random.seed? to ensure replicability between both runs?
* If you use Jupyter Notebook instead of Lab, do you have the same issue?

I use jupyter Lab and Eclipse with Pydev as my IDE. I have never experienced the problem you describe.
