### ISSUE TITLE
Vensim DLL error

### ISSUE THREAD

**Issue by steipatr** [quaquel/EMAworkbench#96]
Hi Jan,

We are using the Workbench to do some experiments on an existing Vensim model. However, we are struggling to get EMA and Vensim working, repeatedly encountering the error `Reinstall Vensim (error 977).` So far we have tried:
- (multiple times) reinstalling Vensim with admin privileges, manually cleaning any DLLs out of `Windows/SysWOW64` and `Windows/System32` in between as described in #55 
- having the DLL file `vendll64.dll` in both or just one of the folders mentioned above
- switching to Python 32bit (3.8.something) and Vensim DSS 8.2 32bit

None of which have shown any success. Are there any other issues you were aware of that might be causing this error?

Specs:
- Windows Server 2019 Datacenter x64, running on Google Cloud Platform
- Python 3.8.5 x64, installed with Miniconda
- Vensim DSS 8.2.1 x64, evaluation license (waiting for funding to clear to get full license)

**Comment by quaquel** [comment]
I know of others who have been having similar issues. It seems very dependent on the specifics of your machine. A fresh install of everything on one machine works fine, while on another it fails. It also is a problem that has been seen before with version 8.01 or so of Vensim in which case it was a bug in the Vensim DLL. Regardless, because it is so machine specific, debugging this is very difficult. 

Can you give me a full overview of what versions of vensim, windows, and python / conda you are using

**Comment by steipatr** [comment]
Sure, here is our current setup:

OS: Microsoft Windows Server 2019 Datacenter 10.0.17763 Build 17763
Vensim: Vensim DSS for Windows Version 8.2.0 Double Precision x64
Python: 3.8.5 build h5fd99cc_1
EMA: 2.0.8 build pypi_0
conda: 4.9.2 build py38haa95532_0

This is all running on Google Cloud Platform. We installed Vensim and Python from an admin account, and are using non-admin accounts for actual work.

**Comment by BenjaminSchoemaker** [comment]
Hi Jan,

As we discussed by e-mail I am encountering the same problem. 

Vensim: Vensim DSS 8.2.0 Double Precision x64 (TU Delft license)
Windows: Windows 10 (Version 20H2 build 19042.685)
Python: 3.8.5 build h5fd99cc_1
EMA workbench: 2.0.8 build pypi_0   
conda: 4.9.2 build py38haa95532_0

**Comment by jasonrwang** [comment]
Replicated the same issue on another desktop using the same approach.

OS: Microsoft Windows 10 Pro 1909 (18363.1316)
Vensim: Vensim DSS for Windows Version 8.2.0 Double Precision x64
Python: 3.8.6 h7840368_4
EMA: 2.0.8 (unknown build)
conda: 4.9.2 (unknown build)

**Comment by steipatr** [comment]
On advice from Ventana, we tried running our tests directly from the admin account (the account with which we installed Vensim), and that seems to work. We'll do some more testing, just posting this here for @BenjaminSchoemaker and anyone else who might be wondering.

**Comment by jasonrwang** [comment]
> On advice from Ventana, we tried running our tests directly from the admin account (the account with which we installed Vensim), and that seems to work. We'll do some more testing, just posting this here for @BenjaminSchoemaker and anyone else who might be wondering.

To be clear, on our Windows 2019 Server OS, we installed while logged in as admin. On Windows 10 Pro, we were logged in as a non-admin user and installed there. A prompt came up for an admin's credentials, and we entered it in to complete the installation.

**Comment by quaquel** [comment]
That is useful information. So there might be something with admin credentials and the DLL. @jasonrwang what you described on you machine, did that solve your problem on the Windows10 machine or not?

Also, completely unrelated, @jasonrwang and @steipatr what are the two of you up to that involves running vensim on Google Cloud machines.....

**Comment by BenjaminSchoemaker** [comment]
@steipatr Thanks! And how did you run your script then? Via the command prompt or do you use a command in Python to run as administrator. When I try running from the command prompt I get an error "DLL load failed while importing _multiarray_umath: the specified module could not be found."

**Comment by steipatr** [comment]
@BenjaminSchoemaker we're still running tests with Jupyter notebook at this point. Haven't tested command line scripts yet. Hope to get around to that tonight, will report here how things go.

**Comment by steipatr** [comment]
@BenjaminSchoemaker I can run python command line scripts without any errors, at least sequentially. Haven't tried parallel processing with multiprocessing yet.

**Comment by BenjaminSchoemaker** [comment]
@steipatr Thanks for the update! Glad it works. Can't say the same for myself yet. What script/commands do you use in Python then to run as admin?

**Comment by steipatr** [comment]
@BenjaminSchoemaker I just logged into the admin account, and ran my script in the anaconda prompt with `python testscript.py`.

**Comment by BenjaminSchoemaker** [comment]
@steipatr I see! I log into the admin account directly since this laptop is offered by my company. I've tried running the script as admin from the windows command prompt but that doesn't work.

**Comment by steipatr** [comment]
That makes sense. For what it's worth, Google Cloud Platform gives you 300$ of free use credits when you register. Might be an option for you?

**Comment by quaquel** [comment]
> @steipatr Thanks! And how did you run your script then? Via the command prompt or do you use a command in Python to run as administrator. When I try running from the command prompt I get an error "DLL load failed while importing _multiarray_umath: the specified module could not be found."

can you show a more complete track trace. This sounds like a numpy DLL issue, not vensim DLL related.

**Comment by BenjaminSchoemaker** [comment]
@quaquel You may be right. This is the complete track trace:

C:\Users\b.schoemaker\Anaconda3\lib\site-packages\numpy\__init__.py:138: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "simple_model_ema_script.py", line 13, in <module>
    from ema_workbench import (TimeSeriesOutcome, perform_experiments,
  File "C:\Users\b.schoemaker\Anaconda3\lib\site-packages\ema_workbench\__init__.py", line 1, in <module>
    from . import em_framework
  File "C:\Users\b.schoemaker\Anaconda3\lib\site-packages\ema_workbench\em_framework\__init__.py", line 16, in <module>
    from .outcomes import (ScalarOutcome, TimeSeriesOutcome, Constraint,
  File "C:\Users\b.schoemaker\Anaconda3\lib\site-packages\ema_workbench\em_framework\outcomes.py", line 10, in <module>
    import pandas
  File "C:\Users\b.schoemaker\Anaconda3\lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\Users\b.schoemaker\Anaconda3\python.exe"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: Kan opgegeven module niet vinden.

**Comment by jasonrwang** [comment]
@BenjaminSchoemaker I ran into the same issue with you while trying to debug a `.py` file to run EMA-Vensim over multiple threads. The VS Code debugger created a new debugging terminal and environment that was not loading my Conda environment properly, which is a known issue over at https://github.com/microsoft/vscode-python/issues/13262. I fixed it by the following running commands in Git Bash before trying to debug again in VS Code.

I don't know if your case is the same, but it resolved my numpy DLL problem.

```bash
conda activate JasonEnvironmentName
cd /c/users/ProjectDirectory
code .
```

**Comment by rogersamso** [comment]
Same issue here (`Reinstall Vensim (error 977)`) with Vensim Model Reader, while with Vensim DSS it worked flawlessly.
Do you know if there's some particularity of the Vensim Model Reader DLL that would make it incompatible with the workbench?

**Comment by quaquel** [comment]
To my knowledge you need Vensim DSS and model reader has never worked.

**Comment by rogersamso** [comment]
Apparently the Vensim Model Reader also has support for the DLL (https://vensim.com/vensim-model-reader/).

> The model reader can also be used to open published Venapps and to open other applications that use the Vensim DLL. 

But now I know it has not been tested.
Thanks!
